Numpy - Broadcasting

In [1]:
import numpy as np
a = np.array([0,1,2])
b = np.array([5,5,5])

In [2]:
a+b

array([5, 6, 7])

In [3]:
# broadcasting allows these kind of element by element basis operations to be performed on arrays of different sizes

In [5]:
# adding a scalar
a+5

array([5, 6, 7])

In [8]:
# create a matrix 3x3 (all elements =1)
M=np.ones((3,3))

In [14]:
M

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [15]:
# create an array of 3 elements (vector)
a

array([0, 1, 2])

In [16]:
# by broadcasting, we can still preform the operation below:
M+a

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [20]:
# Look at another example versus broadcasting rules:
# M matrix 2x3
M = np.ones((2,3))
M

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [21]:
# a: one dimensional array
a = np.arange(3)
a

array([0, 1, 2])

In [22]:
M.shape

(2, 3)

In [23]:
a.shape

(3,)

In [24]:
# rule 1 in the broadcasting list
# a is the smallest and will end up having dimensions (1,3)
# rule 2:
# a is streched to (2,3)
# now they can be added

In [18]:
# the rule can break down. Ex:
# you cannot add a matrix (2,3) and matrix (3,2)
# it will pass rule 1, but fails rule2 because none of them has 1 as dimensions

In [25]:
# NOTE:
# a_3 below is not a matrix 1x3, it is an array with 1 dimension (a vector)

In [29]:
# M below is an array matrix, with 2 dimensions
M=np.ones((1,3))
M

array([[ 1.,  1.,  1.]])

In [31]:
# a_3 below looks the same, but in reality it is a 1-dimension array
a_3=np.array([1,1,1])
a_3

array([1, 1, 1])

In [35]:
# indeed if we call index[0] we will get different results for a_3 and M
a_3[0]
# we have first element of the array

1

In [36]:
M[0]
# we have all elements in row 0

array([ 1.,  1.,  1.])