Numpy

NUMPY is the Python response to Matlab
(which was popular with ingeneers, statisticians and other communities)
Matlab is a vectorial language.

In Python they wanted to build a library which could compete with Matlab and R. 
Numpy arrays are the equivalent to vectors in Matlab or R.
Numpy lists are much more efficient than Python lists (python is a dynamic language and in a list we cannot
assume the types of variables and therefore they are less efficient).
                                                       
We can also apply many more functions in Numpy.


In [1]:
import numpy as np

In [2]:
# Create an array
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
# ex above is a convenient way to start an array (with zeros)

In [4]:
# create a matrix 3rows by 5 columns
np.ones((3,5),dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [5]:
# create a lists of lists with list
# instead of using numpy
list1 = []
for i in range(3):
    list_row=[]
    for j in range(5):
        list_row.append(1)
        list1.append(list(list_row))

In [6]:
list1
# (but this is not a matrix)

[[1],
 [1, 1],
 [1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1],
 [1, 1],
 [1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1],
 [1, 1],
 [1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 1, 1]]

In [7]:
# i can fill my matrix with numbers different than 0 or 1 as
np.full((3,4),3.14)

array([[ 3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14]])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# ex go from 0 to 1, in 5 steps
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [14]:
# numbers from 0 to 100, every 10
np.linspace(0,100,11)

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.])

In [16]:
# create matrix 3x3 filled with random numbers
np.random.random((3,3))

array([[ 0.64091791,  0.5401857 ,  0.89790734],
       [ 0.69399657,  0.41597074,  0.95458007],
       [ 0.81049399,  0.9704841 ,  0.63889434]])

In [18]:
np.random?
# use ? to look up info

In [19]:
np.random.normal(0,1,(3,3))
# create matrix 3,3 with random samples from a normal distribution
# defined by: mean (0) and stdev (1)

array([[ 0.95605357,  1.0854332 ,  0.84659444],
       [-2.28736272,  1.09015891,  0.77330713],
       [ 1.94285271, -0.63463374, -0.35216816]])

In [20]:
# normal distribution:
# can be fully described by 2 terms only:
# average and standard deviation (how different is everything from the average)

In [21]:
np.random.normal(0,10,(3,3))

array([[ -2.34100941,  -8.70606297,  14.03628618],
       [  8.5191929 ,   4.42570944,   3.33074867],
       [-13.44927108,  12.0154728 ,  -6.62086468]])

In [22]:
np.random.randint(0,10,(3,3))
# create a matrix 3x3 filled by random integers between 0 and 10

array([[7, 9, 8],
       [1, 4, 4],
       [9, 2, 7]])

In [23]:
# create identity matrix 3x3
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [24]:
# identity matrix
# if multiplied with an original matrix it returns the original matrix

In [25]:
np.empty(16)

array([  4.67296746e-307,   1.69121096e-306,   9.34604357e-307,
         7.56596412e-307,   1.42418987e-306,   1.37961641e-306,
         1.60220528e-306,   1.24611266e-306,   9.34598925e-307,
         1.24612081e-306,   1.11260755e-306,   1.60220393e-306,
         1.51320640e-306,   9.34609790e-307,   1.86921279e-306,
         1.24610723e-306])

In [35]:
# what does np.empty do?
# takes the value of memory blocks in my pc and interpret them as numbers
#
# creating randomness is very difficult
# a computer really generates only pseudo-randomness
# a scientist said that a PC, beeing deterministic, cannot really create randomness

In [38]:
# the one above is a cheaper way to create an array

In [29]:
# we can put different types in the arrays (int, float, boolean)
# but all elements in the array must be of the same type

# ex: create an array of False (False=0)
np.zeros(10, dtype=bool)

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [32]:
# ex: create an array of True (no0)
np.ones(10, dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [33]:
# array vector
np.random.randint(10,size=6)

array([7, 7, 0, 6, 4, 6])

In [40]:
# 3 dimensional matrix
x1= np.random.randint(10, size=(3,4,5))

In [41]:
x1

array([[[0, 1, 3, 9, 2],
        [3, 7, 6, 9, 5],
        [0, 4, 6, 4, 0],
        [6, 6, 3, 4, 4]],

       [[1, 6, 9, 9, 9],
        [5, 6, 9, 7, 4],
        [0, 6, 9, 7, 8],
        [8, 6, 9, 7, 4]],

       [[0, 7, 1, 6, 6],
        [4, 5, 1, 9, 0],
        [8, 7, 9, 8, 9],
        [8, 3, 4, 9, 4]]])

In [42]:
# to check array dimensions
x1.ndim

3

In [43]:
# to check shape
x1.shape

(3, 4, 5)

In [44]:
x1.size

60

In [45]:
# to check type of elem
x1.dtype

dtype('int32')

In [46]:
# access element inside matrix
# take first array, row 3 and column 2 (remember first row is 0 and first column is 0)
x1[0][3][2]

3

In [47]:
# to modify array, I make the elem above equal to 6
x1[0][3][2]=6

In [48]:
x1

array([[[0, 1, 3, 9, 2],
        [3, 7, 6, 9, 5],
        [0, 4, 6, 4, 0],
        [6, 6, 6, 4, 4]],

       [[1, 6, 9, 9, 9],
        [5, 6, 9, 7, 4],
        [0, 6, 9, 7, 8],
        [8, 6, 9, 7, 4]],

       [[0, 7, 1, 6, 6],
        [4, 5, 1, 9, 0],
        [8, 7, 9, 8, 9],
        [8, 3, 4, 9, 4]]])

In [49]:
x1[0][0][0]=3.14
x1

array([[[3, 1, 3, 9, 2],
        [3, 7, 6, 9, 5],
        [0, 4, 6, 4, 0],
        [6, 6, 6, 4, 4]],

       [[1, 6, 9, 9, 9],
        [5, 6, 9, 7, 4],
        [0, 6, 9, 7, 8],
        [8, 6, 9, 7, 4]],

       [[0, 7, 1, 6, 6],
        [4, 5, 1, 9, 0],
        [8, 7, 9, 8, 9],
        [8, 3, 4, 9, 4]]])

In [50]:
# it has used 3 because I have specified earlier type as integer
# the number 3,14 is simply truncated to 3

In [51]:
# slicing
x=np.arange(10)

In [52]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# take from elem 4 to elem 6
x[4:7]

array([4, 5, 6])

In [55]:
x2=np.random.randint(10,size=(5,5))
x2

array([[2, 7, 4, 5, 8],
       [6, 9, 2, 0, 4],
       [3, 8, 6, 2, 5],
       [2, 1, 0, 6, 2],
       [4, 9, 7, 4, 2]])

In [56]:
x2[:2,:3]
# multidimentional slice
# row 0 and 1
# column 0 1 2

array([[2, 7, 4],
       [6, 9, 2]])

In [58]:
# exercise
# what will this give me?
x2[3:,2:]

array([[0, 6, 2],
       [7, 4, 2]])

In [59]:
x2[::2,::2]
# beginning to last row but take every other
# same for columns

array([[2, 4, 8],
       [3, 6, 5],
       [4, 7, 2]])

In [60]:
# to access all row or column

# ex to access all first column
x2[:,0]

array([2, 6, 3, 2, 4])

In [61]:
# last column
x2[:,-1]

array([8, 4, 5, 2, 2])

In [63]:
# to access row 2
x2[2]

array([3, 8, 6, 2, 5])

In [64]:
x2_col = x2[:,0]

In [65]:
x2_col

array([2, 6, 3, 2, 4])

In [66]:
x2_col[0]=1

In [67]:
x2_col

array([1, 6, 3, 2, 4])

In [69]:
x2
# if i check x2 again, I can see that 2 has been modified with 1 also there

array([[1, 7, 4, 5, 8],
       [6, 9, 2, 0, 4],
       [3, 8, 6, 2, 5],
       [2, 1, 0, 6, 2],
       [4, 9, 7, 4, 2]])

In [70]:
# important:
# numpy array slicing returns 'views' on the original list, rather than copies,
# unlike python lists that return decoupled copies when sliced
list1 = [1,2,3,4,5]
list2 = list1[0:2]
list2[0]=7
list1

[1, 2, 3, 4, 5]

In [71]:
list2

[7, 2]

In [72]:
# how do i copy then a matrix?
x2_copy = x2.copy()

In [73]:
x2_copy

array([[1, 7, 4, 5, 8],
       [6, 9, 2, 0, 4],
       [3, 8, 6, 2, 5],
       [2, 1, 0, 6, 2],
       [4, 9, 7, 4, 2]])

In [75]:
x2_copy[0][0]=19
x2_copy

array([[19,  7,  4,  5,  8],
       [ 6,  9,  2,  0,  4],
       [ 3,  8,  6,  2,  5],
       [ 2,  1,  0,  6,  2],
       [ 4,  9,  7,  4,  2]])

In [77]:
x2
# now my x2 matrix has not been modified

array([[1, 7, 4, 5, 8],
       [6, 9, 2, 0, 4],
       [3, 8, 6, 2, 5],
       [2, 1, 0, 6, 2],
       [4, 9, 7, 4, 2]])

In [78]:
x2_column_copy=x2[:,0].copy()

In [79]:
x2_column_copy # is now decoupled from original list, i.e. no longer a 'view'

array([1, 6, 3, 2, 4])

---

Reshaping arrays, concatenating and splitting

In [80]:
one_row=np.arange(1,10)

In [81]:
one_row

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
one_row.size

9

In [83]:
# i want to transform it in a 3x3 matrix
reshaped_above=one_row.reshape((3,3))
reshaped_above

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
# i want to go back to original
original_ar=reshaped_above.reshape((1,9))
original_ar

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [86]:
# Note: it gives you an error if you want to reshape it for example in 2 by 6 as not correct number of samples

In [88]:
x = np.array([1,2,3])

In [89]:
y = np.array([19,20,21])

In [90]:
np.concatenate([x,y])

array([ 1,  2,  3, 19, 20, 21])

In [91]:
# I can concatenate the arrays above in more comple ways. Ex:
np.concatenate([x,y,x,x]).reshape(4,3)

array([[ 1,  2,  3],
       [19, 20, 21],
       [ 1,  2,  3],
       [ 1,  2,  3]])

In [92]:
# splitting arrays
x = [1,2,3,3,99,2,1]

In [93]:
x1,x2,x3 = np.split(x,[3,5])

In [94]:
print(x1,x2,x3)

[1 2 3] [ 3 99] [2 1]


In [95]:
# above: split in 3 places, the first position in 3, then 5 then till the end

---

 Aggregate functions

In [96]:
L = np.random.random(100)

In [97]:
# sum all elements
sum(L)

48.006055762130202

In [98]:
# sum in numpy
np.sum(L)

48.006055762130217

In [99]:
# compare how long sum took
%timeit sum(L)

10000 loops, best of 3: 21.4 µs per loop


In [100]:
% timeit np.sum(L)

The slowest run took 12.23 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.96 µs per loop


In [101]:
L_million = np.random.random(1000000)

In [102]:
% timeit sum(L_million)

1 loop, best of 3: 201 ms per loop


In [103]:
% timeit np.sum(L_million)

1000 loops, best of 3: 1.34 ms per loop


In [104]:
# L is a row
L.shape

(100,)

In [105]:
# aggregate: min, max
# numpy only aggregates: np.prod, np.mean, np.std,np.var, np.media, np.percentile, np.any, np.all

In [106]:
# i want to create an array of random True and False
# i create integers 0 or 1, size 10, and then make them boolean (True or False)
my_np_ar=np.random.randint(0,2, size=10, dtype=bool)

In [107]:
my_np_ar

array([ True, False, False,  True,  True,  True, False,  True, False,  True], dtype=bool)

In [108]:
np.any(my_np_ar)

True

In [109]:
np.all(my_np_ar)

False

In [110]:
# np.any and np.all looks at logic
# any: True if any of the booleans is True
# all: True if all of the booleans are True
# (note: in Python 0 is considered false, anything else True)

---

Exercise

In [112]:
# Exercise
# using president_heights csv file
# which has been copied in same folder where running this jupyter notebook
# use command
# %ls
# to check directory and content

In [114]:
# !head -4 president_heights.csv
# not working in Windows

In [115]:
# using pandas to import csv
import pandas as pd

In [116]:
my_data=pd.read_csv('president_heights.csv')

In [117]:
import numpy as np
heights = np.array([my_data['height(cm)']])

In [118]:
heights

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
        183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
        188, 182, 185]], dtype=int64)

In [119]:
# !tail -4 president_heights.csv
# not working in Windows

In [124]:
# Exploring data (head, tail, mean, stdv)
my_data.head(6)

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183
5      6  John Quincy Adams         171

In [125]:
my_data.tail(6)

order               name  height(cm)
36     39       Jimmy Carter         177
37     40      Ronald Reagan         185
38     41  George H. W. Bush         188
39     42       Bill Clinton         188
40     43     George W. Bush         182
41     44       Barack Obama         185

In [126]:
heights.mean()

179.73809523809524

In [127]:
heights.std()

6.9318434427458921

In [128]:
# most of them are 179 plus or minus 6.9

In [129]:
heights.min()

163

In [130]:
heights.max()

193

In [131]:
np.percentile(heights,25)

174.25

In [132]:
np.percentile(heights, 75)

183.0

In [133]:
heights

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
        183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
        188, 182, 185]], dtype=int64)

In [134]:
%matplotlib inline
import matplotlib.pyplot as plt

In [137]:
# try to plot data
# plt.hist(heights)