NUMPY - Universal functions

In [1]:
# universal functions are numpy equivalent of 'vectorised operations' in Matlab and R
# These are operations that are executed on each cell of the matrix/vector
# Universal functions exploit numpy's optimised arrays to execute operations in a much quicker way
# than in the equivalent list/row numpy way.

In [2]:
# exercise
# Compute reciprocals using python lists
# Compute reciprocals using numpy arrays (with indexes)
# compare time it takes for the two processes to run

In [3]:
def compute_reciprocals(values):
    '''Takes a list of float values and returns a list with reciprocals of the numb
    in the list and puts the value NaN when the value it is reciprocating is 0'''
    list_rec=[]
    for i in values:
        if i==0:
            list_rec.append('Nan')
        else:
            list_rec.append(1/i)
    return list_rec
    # example: [4,0,1] returns [0.25, 'Nan',1]
    #print(list_rec)

In [4]:
compute_reciprocals([4,0,1])

[0.25, 'Nan', 1.0]

In [5]:
# Now do the exercise above using Numpy
import numpy as np

In [6]:
def numpy_compute_recip(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        if values[i]==0:
            output[i]='NaN'
        else:
            output[i]=1.0/values[i]
    return output
    #print(output)

In [7]:
my_values = np.random.randint(1,10,size=5)
my_values

array([9, 2, 1, 6, 5])

In [8]:
numpy_compute_recip(my_values)

array([ 0.11111111,  0.5       ,  1.        ,  0.16666667,  0.2       ])

In [9]:
# create now a new list and a new aray of 1000000 random numbers
big_array=np.random.randint(1,100,size=1000000)

In [10]:
# make it a list
big_array_list=list(big_array)

In [11]:
# we want to time them
%timeit numpy_compute_recip(big_array)

1 loop, best of 3: 2.97 s per loop


In [12]:
%timeit compute_reciprocals(big_array_list)

1 loop, best of 3: 583 ms per loop


In [13]:
# when comparing same task carried out with list or numpy
# numpy is much slower then computing with list above

In [14]:
# so why do we use numpy?

---

Vectorised operation or universal function

In [15]:
print(1.0/big_array)

[ 0.01960784  0.01388889  0.03030303 ...,  0.01639344  0.05555556
  0.07142857]


In [16]:
%timeit 1.0/big_array

100 loops, best of 3: 5.9 ms per loop


In [17]:
5.0/big_array
# it knows to apply operation to each term of the array

array([ 0.09803922,  0.06944444,  0.15151515, ...,  0.08196721,
        0.27777778,  0.35714286])

In [18]:
2.7**big_array
# e to the power of numb in big_array

array([  9.98968910e+21,   1.14338113e+31,   1.71792507e+14, ...,
         2.05678840e+26,   5.81497370e+07,   1.09418989e+06])

In [19]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b = np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
a/b

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ,
        0.83333333,  0.85714286,  0.875     ,  0.88888889,  0.9       ])

In [22]:
np.arange(5)/np.arange(1,6)

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

In [23]:
x = np.arange(9).reshape(3,3)

In [24]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [26]:
x+2*x

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [27]:
np.ufunc?

In [28]:
# very often you have a function that you want to apply to all matrix
y = np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
z = x+2*x+x**y
z
# 0 + 2*0 + 0squared by 0
# 1 + 2*1 + 1 squared 2

array([[       1,        4,       10],
       [      36,      268,     3140],
       [   46674,   823564, 16777240]])

In [31]:
# sometimes you see ufunct defined as follows
np.add(x,2)
# for every entry of x add 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [32]:
# same as:
x+2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [33]:
# other ufunct:
# np.subtract, np.negative, np.multiply, np.divide, np.floor_divide, np.power, np.mod
# np.sin, np.cos, np.power, np.exp, np.logs