Numpy - Boolean Masks

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [3]:
x < 3

array([ True,  True, False, False, False], dtype=bool)

In [4]:
# the condition x < 3 is considered for each elem in the array

In [5]:
x ==3

array([False, False,  True, False, False], dtype=bool)

In [6]:
x != 3

array([ True,  True, False,  True,  True], dtype=bool)

In [7]:
# I can apply more complicated conditions. Ex:
(2*x) == (x**2)
# to know for which element the element multiplied by 2 is equal to its square

array([False,  True, False, False, False], dtype=bool)

In [8]:
# This is quicker than writing complex functions
# And it is much more readable

In [10]:
# to know how many Trues when x<3 (0 in Python is false, non zero means True)
np.count_nonzero(x<3)

2

In [11]:
np.sum(x<3)
# counting in x<3 how many Trues =1 and false=0

2

In [16]:
# create a 3x4 matrix of random integer numbers
rng = np.random.RandomState(0)
x= rng.randint(10, size=(3,4))

In [17]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [18]:
np.all(x<8, axis=1)
# where axis=1 means rows

array([ True, False,  True], dtype=bool)

In [19]:
# above: set to True if all numbers in the row are less then 8 and do the same for each row of the matrix

In [21]:
np.all(x<6, axis=0)
# ...if all numbers in the column are less then 6 and do it for each column
# axis=0 means columns

array([False, False, False, False], dtype=bool)

In [22]:
# example

In [23]:
# we want to know all the numbers which are less then 5
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [24]:
x[x<5]
# MASK: you index on a condition rather than a position.
# It means: give me back all the numbers that satisfy condition x<5
# Within [] I am not writing the index, but the condition

array([0, 3, 3, 3, 2, 4])

In [25]:
# to see where they are however i have to do
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]], dtype=bool)